### ISSUE TITLE
Not generatin AP

### ISSUE THREAD

**Issue by zeeshan7860** [s0meguy1/RougeWifi#2]
it is stuck at starting hostapd
it is generating AP but not showing captive portal or redirecting to the page

**Comment by reaperNorman** [comment]
The problem is that the interface you're trying to run is not in monitor mode.

I fixed this issue by running airmon-ng start {interface}. Then running ./wifi.sh {interface} {internet} {AP name}.

**Comment by james0301** [comment]
Sirs can you please help me, i've created the AP but when i connect using my phone, there is no captive porta that pops up. Hope that you can help me

**Comment by s0meguy1** [comment]
Closing, not maintaining this anymore
